pipeline {
    environment { 
        ENV1 = 'env1'
    }
    parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')
        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')
        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    }
    agent any
    stages {
        stage('Using Parameters') {
            steps {
                echo "Hello ${params.PERSON}"
                echo "Biography: ${params.BIOGRAPHY}"
                echo "Toggle: ${params.TOGGLE}"
                echo "Choice: ${params.CHOICE}"
                echo "Password: ${params.PASSWORD}"
            }
        }
        stage('Using Environment1') {

            // 해당 stage 내에서만 environment 사용가능
            environment { 
                ENV2 = 'env2'
            }
            steps {
                sh '''
                echo "$ENV1";
                echo "$ENV2";
                '''
            }
        }
        stage('Using Environment2') {
            steps {
                sh '''
                echo "$ENV1";
                echo "$ENV2";
                '''
            }
        }
    }
}